from mongoengine.fields import (
    ListField,
    StringField,
    IntField,
    FloatField,
    EmbeddedDocument
)


class Metrics(EmbeddedDocument):
    categorised_difficulty = StringField()
    imports = ListField(StringField())
    calls = ListField(StringField())
    difficulty = FloatField()
    no_of_functions = IntField()
    loc = IntField()
    lloc = IntField()
    sloc = IntField()

    # counts
    importFromCount = IntField()
    expressionCount = IntField()
    classDefCount = IntField()
    returnCount = IntField()
    deleteCount = IntField()
    assignCount = IntField()
    augAssignCount = IntField()
    annAssignCount = IntField()
    forCount = IntField()
    asyncForCount = IntField()
    whileCount = IntField()
    ifCount = IntField()
    withCount = IntField()
    asyncWithCount = IntField()
    raiseCount = IntField()
    tryCount = IntField()
    assertCount = IntField()
    globalCount = IntField()
    nonlocalCount = IntField()
    exprCount = IntField()
    passCount = IntField()
    breakCount = IntField()
    continueCount = IntField()
    sliceCount = IntField()
    boolOpCount = IntField()
    binOpCount = IntField()
    unaryOpCount = IntField()
    lambdaCount = IntField()
    ifExpCount = IntField()
    dictCount = IntField()
    setCount = IntField()
    listCompCount = IntField()
    setCompCount = IntField()
    dictCompCount = IntField()
    generatorExpCount = IntField()
    awaitCount = IntField()
    yieldCount = IntField()
    yieldFromCount = IntField()
    compareCount = IntField()
    formattedValueCount = IntField()
    joinedStrCount = IntField()
    constantCount = IntField()
    attributeCount = IntField()
    subscriptCount = IntField()
    starredCount = IntField()
    nameCount = IntField()
    listCount = IntField()
    tupleCount = IntField()
    delCount = IntField()
    loadCount = IntField()
    storeCount = IntField()
    andCount = IntField()
    orCount = IntField()
    addCount = IntField()
    bitAndCount = IntField()
    bitOrCount = IntField()
    bitXorCount = IntField()
    divCount = IntField()
    floorDivCount = IntField()
    lShiftCount = IntField()
    modCount = IntField()
    multCount = IntField()
    matMultCount = IntField()
    powCount = IntField()
    rShiftCount = IntField()
    subCount = IntField()
    invertCount = IntField()
    notCount = IntField()
    uAddCount = IntField()
    uSubCount = IntField()
    eqCount = IntField()
    gtCount = IntField()
    gtECount = IntField()
    inCount = IntField()
    isCount = IntField()
    isNotCount = IntField()
    ltCount = IntField()
    ltECount = IntField()
    notEqCount = IntField()
    notInCount = IntField()
    comprehensionCount = IntField()
    exceptHandlerCount = IntField()
    argumentsCount = IntField()
    argCount = IntField()
    keywordCount = IntField()
    aliasCount = IntField()
    withitemCount = IntField()
    indexCount = IntField()
    suiteCount = IntField()
    augLoadCount = IntField()
    augStoreCount = IntField()
    paramCount = IntField()
    numCount = IntField()
    strCount = IntField()
    bytesCount = IntField()
    nameConstantCount = IntField()
    ellipsisCount = IntField()
